apiVersion: apps/v1
kind: Deployment
metadata:
  name:  appname
spec:
  selector:
    matchLabels:
      app:  appname
  template:
    metadata:
      labels:
        app:  appname
    spec:
      containers:
        - name:  appname
          image: imageName # IMPORTANT: Update!
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  appname
  name:  svcname
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app:  appname
