apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: demo-app
spec:
  host: a65075e33155e4d44a3c13b92056a793-284587433.us-west-2.elb.amazonaws.com
  tls:
    secret: bos-secret
    redirect: 
      enable: true
      code: 301
  upstreams:
  - name: existing-svc
    service: existing-svc
    port: 80
  - name: new-svc
    service: new-svc
    port: 80
  routes:
  - path: /
    matches:
    - conditions:
      - header: release
        value: beta
      action:
        pass: new-svc
    action:
      pass: existing-svc
