apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bank-of-sirius
spec:
  host: elb-hostname
  tls:
    secret: sirius-secret
    redirect: 
      enable: true
      code: 301
  upstreams:
  - name: new-svc
    service: new-svc
    port: 80
  routes:
  - path: /
    action:
      pass: new-svc