apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: demo-app
spec:
  host: demo.example.com
  upstreams:
  - name: new-svc
    service: new-svc
    port: 80
  routes:
  - path: /
    action:
      pass: new-svc
      