apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bank-of-sirius
spec:
  host: elb-hostname
  tls:
    secret: sirius-secret
    redirect: 
      enable: true
      code: 301
  upstreams:
  - name: existing-svc
    service: existing-svc
    port: 80
  - name: new-svc
    service: new-svc
    port: 80
  routes:
  - path: /
    splits:
    - weight: old-weight
      action:
        pass: existing-svc
    - weight: new-weight
      action:
        pass: new-svc
